version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: teste-visu
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visu_clientes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dados-mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
    driver: local

